### ISSUE TITLE
500 Error on login

### ISSUE THREAD

**Issue by mpn-peter-smith** [joshp23/YOURLS-OIDC#2]
Hi,
After I have logged in via openid I get redirected to the yourls login page instead of getting logged in. Attempting to click login creates a 500 error.

**Comment by joshp23** [comment]
I wonder what your setup configuration is here. It is important to make sure that the redirects are set up correctly in the OIDC server.

In order to troubleshoot this further, YOURLS log files corresponding to the 500 error would be helpful. as would any data from your OIDC server implementation. I did only test this against Keycloack.

**Comment by joshp23** [comment]
Did you update your PHP lately? Check dependencies if so.

**Comment by mpn-peter-smith** [comment]
PHP version 7.4
I am using Keycloak as my OIDC provider.

**Comment by joshp23** [comment]
> The web server log files corresponding to the 500 error would be helpful.

**Comment by GrafikPat** [comment]
Hey I'm having the same error but at the beginning, before logging in.

`[Mon Mar 10 19:00:28.576438 2025] [proxy_fcgi:error] [pid 3201229:tid 3201229] [client **************] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Jumbojett\\OpenIDConnectClientException: The provider authorization_endpoint could not be fetched. Make sure your provider has a well known configuration available. in /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:633\nStack trace:\n#0 /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(594): Jumbojett\\OpenIDConnectClient->getWellKnownConfigValue()\n#1 /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(742): Jumbojett\\OpenIDConnectClient->getProviderConfigValue()\n#2 /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(419): Jumbojett\\OpenIDConnectClient->requestAuthorization()\n#3 /YOURLS/user/plugins/oidc/plugin.php(28): Jumbojett\\OpenIDConnectClient->authenticate()\n#4 /YOURLS/includes/functions-plugins.php(221): oidc_auth()\n#5`

`// oidc server
define( 'OIDC_BASE_URL', 'https://auth.domain.tld/application/o/yourls/.well-known/openid-configuration' );
define( 'OIDC_CLIENT_NAME', '************' );
define( 'OIDC_CLIENT_SECRET', '***********' );
// Option 1: link OIDC users to local YOURLS users
#$oidc_profiles = array( 
#'YOURLS_UNAME' => 'sub attribute from OIDC provider',
#);
// Option 2, all users on OIDC platform have YOURLS accounts. uses 'preferred_username' attribute
define( 'OIDC_BYPASS_YOURLS_AUTH', true );`

Do I need to remove the ".well-known/openid-configuration" part?
The Auth server used here is Authentik.

Edit: Indeed removing ".well-known/openid-configuration" did help it but now im stuck at the same problem.

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Jumbojett\\OpenIDConnectClientException: The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client in /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php:316\nStack trace:\n#0 /YOURLS/user/plugins/oidc/plugin.php(28): Jumbojett\\OpenIDConnectClient->authenticate()\n#1 //YOURLS/includes/functions-plugins.php(221): oidc_auth()\n#2 /YOURLS/includes/functions-auth.php(93): yourls_apply_filter()\n#3 /YOURLS/includes/auth.php(5): yourls_is_valid_user()\n#4 /YOURLS/includes/functions-auth.php(15): require_once('...')\n#5 /YOURLS/yourls-infos.php(5): yourls_maybe_require_auth()\n#6 {main}\n  thrown in /YOURLS/user/plugins/oidc/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php on line 316', referer:domain.ltd?code=xxxxxx`

Edit (again):
seems like the define( 'OIDC_BYPASS_YOURLS_AUTH', true ); doesn't work.
is it a layer 8 problem? Config error? :)

Edit:
I've tried a bit and it seems like that there is something i dont quiet understand about the config. If someone could explain....

**Comment by Dherlou** [comment]
I also couldn't get Authentik to work with any of the existing solutions (like this OIDC plugin), so I developed a reverse proxy auth plugin for yourls that parses authentication information from a header provided by a reverse proxy (like Traefik) that can also utilize authentication middleware (like Authentik):

https://github.com/Dherlou/Yourls-Reverse-Proxy-Auth

The regex in the example setup probably needs some more tweaking to only allow bypassing authentication for Short-URLs, that do not match any existing files or the `/admin` area), but unfortunately Authentik uses GoLang Regex interpreter, which doesn't support negative lookaheads. However, this should be a good starting point in case anyone looks for a similar solution.
